### ISSUE TITLE
shopping list integration to `todo` doesn't seem to work. `todo` entities are either `0` or `unavailable`.

### ISSUE THREAD

**Issue by jeroenterheerdt** [Anrolosia/Shopping-List-with-Grocy#46]
![Image](https://github.com/user-attachments/assets/2831cde9-4f8c-4749-abec-221e7e26542f)

Seeing this in the log:
```
This error originated from a custom integration.

Logger: custom_components.shopping_list_with_grocy.coordinator
Source: helpers/update_coordinator.py:393
integration: Shopping List with Grocy (documentation, issues)
First occurred: 11:32:40 AM (4 occurrences)
Last logged: 11:37:10 AM

Error requesting None data: 200, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url='https://192.168.1.XXX:9192/stockoverview'
```

I am on version 0.17.0.

**Comment by Anrolosia** [comment]
Good morning @jeroenterheerdt 

Hummm, ```stockoverview``` is not called in this module... These are the only endpoints used: https://github.com/Anrolosia/Shopping-List-with-Grocy/blob/main/custom_components/shopping_list_with_grocy/apis/shopping_list_with_grocy.py#L702-L708

**Comment by jeroenterheerdt** [comment]
Well the error message clearly originates from your custom integration, so it must be called somehow.
Regardless, I am not getting anything in my lists. Can you help me troubleshoot this? This was working before the last change you made to sync to todo

**Comment by Anrolosia** [comment]
Of course I will! I'm actualy working on a new optimized and improved update, it will come out soon, would you mind waiting for that version?

**Comment by jeroenterheerdt** [comment]
sure, thanks!

**Comment by Anrolosia** [comment]
I just pushed v0.18.0 with a lot of refactoring about performance improvements and new features in HomeAssistant Todo list.
Let me know if you encounter any issue. Also, I added a lot of logs to help debugging

**Comment by Anrolosia** [comment]
Hello @jeroenterheerdt , do you still have your issue?

**Comment by schumi2309** [comment]
I still have the same problem. it remains at zero.
In addition, in grocy, it is impossible to create a new task.
is it due to that?
my todo file remains in error.

**Comment by Anrolosia** [comment]
Hello @schumi2309 
What do you mean by "In addition, in grocy, it is impossible to create a new task."?
I know grocy can manage tasks but that integration only cares about shopping lists, not tasks

**Comment by jeroenterheerdt** [comment]
Can confirm shopping list is still just 0. There is nothing in the logs.

**Comment by schumi2309** [comment]
Ok, I understand that the spots in grocy have nothing to do with the list (I thought so but no, ok)
So, problems with the todo file!
Furthermore, my "SLWG" file no longer exists, it has disappeared. 
how to recover it?

**Comment by Anrolosia** [comment]
Hello, v0.19.0 should fix issues with the TODO list in Home assistant. All shopping list in Grocy should appear in https://<your ha instance>/todo with "SWLG - " prefix, followed by the name of your shopping list in Grocy.

For any other problem, please open a new issue.
