### ISSUE TITLE
Todo ?

### ISSUE THREAD

**Issue by schumi2309** [Anrolosia/Shopping-List-with-Grocy#48]
I just installed version 0.19 but I still have no files created under the name of SLWG.* Before I had 2 files, now, in addition, it added me a file per article, so on my side, for the moment I have 144 files. but no SLWG. It is not created. and I have an error now on the file 
"sensor.shopping_list_items"

entity not provided by integration. what to do? where is the problem please? thank you.

**Comment by Anrolosia** [comment]
I don't get it. Which file are you talking about? The TODO is in https://your-domain-name/todo and should look like something like that

![Image](https://github.com/user-attachments/assets/1bc7d894-2262-4772-9c4a-704a64f768a1)

**Comment by schumi2309** [comment]
yes I know that. but you say that grocy creates a file that starts with SLWG. this file does not exist for me. it does not create it! so what should I do. when I go to todo, it is empty. no list.

**Comment by Anrolosia** [comment]
Well, yeah, I never mentionned a file :) I said it creates a TODO :)
Can you show the configuration of your Grocy instance? Also, are you using my Shopping With Grocy card for HA?
Is there any errors in the logs?
How is configured your shopping list in Grocy?

**Comment by schumi2309** [comment]
![image](https://github.com/user-attachments/assets/78b5776a-023f-48a1-88e7-98e44cdb59e8)

![image](https://github.com/user-attachments/assets/e34a3882-a1f3-4046-b270-76a74ec0e3cb)

![image](https://github.com/user-attachments/assets/71311eed-b665-47e4-8c6f-03964caad0e4)

This ?

**Comment by schumi2309** [comment]
And this 

![image](https://github.com/user-attachments/assets/a0ca3f63-b61c-4470-b475-b33b90862a58)

**Comment by Anrolosia** [comment]
Ok, great!
Seems it's configured as it should.
Could you try update to v0.19.1, restart your home assistant and check?
And if it doesn't work, please check your logs

**Comment by schumi2309** [comment]
ok no worries. but I'll do that when I get home because I'm at work. as soon as I get home I'll install, test, and get back to you. thanks for your help.

**Comment by schumi2309** [comment]
after installation, nothing changes, I still have no shopping list in my TODO.
I don't understand where this comes from.
Here is the only thing I have in my log:

![Image](https://github.com/user-attachments/assets/6953dd42-0d5e-4729-b182-3344b69c23a8)

![Image](https://github.com/user-attachments/assets/6887a050-81b5-4540-82e1-60057ae99b96)

I don't know if this can help you.

**Comment by Anrolosia** [comment]
Yes, it helps! It shows a timeout fetching the data.
Correct me if I'm wrong, but you are using Grocy's home assistant version, right? 
Also, can you enable info logs for my integration please? It should show the initialization of the sensors

**Comment by Anrolosia** [comment]
Also, I checked, the timeout is configured to be triggered after 60s, it's already pretty high... Do you have a big list of items?

**Comment by schumi2309** [comment]
+/- 140 items.

**Comment by Anrolosia** [comment]
Ok, so that's not the issue, I have ~240 items, and it works like a charm
What about my previous message?

**Comment by schumi2309** [comment]
weird thing:
I don't have the first two sensors! 👍 

❌ Product Sensor
ID: sensor.products_shopping_list_with_grocy
Displays the total number of products in Grocy.
Can include product details if enabled during setup.

❌ Shopping List Sensor
ID: sensor.shopping_list_shopping_list_with_grocy
Shows the number of items in your Grocy shopping list.
Can include product details if enabled.

✔️ Updating Sensor
ID: binary_sensor.updating_shopping_list_with_grocy
Indicates if the list is currently being updated.

✔️ Pause Update Switch
ID: switch.pause_update_shopping_list_with_grocy
Temporarily pauses synchronization between Grocy and Home Assistant.

**Comment by Anrolosia** [comment]
> How should I get the log with your add-on? and where to find the log file afterwards?

Open your file editor (module in home assistant), open configuration.yaml and paste:
```
logger:
  default: error
  logs:
    custom_components.shopping_list_with_grocy: info
```
Save and reboot, and then go to settings > logs (/config/logs)

**Comment by schumi2309** [comment]
this ?

logger:
  default: info
  logs:
    custom_components.teamtracker: debug
    custom_components.hacs: debug
    aiogithubapi: debug
    pyaarlo: debug
    custom_components.shopping_list_with_grocy: info

**Comment by Anrolosia** [comment]
yes, but if your logger default is already info, then you should already have more logs than just the one you've sent.
what you can try is to remove the timeout in the code to test. To do so, open your file editor in home assistant, and open /custom_components/shopping_list_with_grocy/coordinator.py and replace [this](https://github.com/Anrolosia/Shopping-List-with-Grocy/blob/main/custom_components/shopping_list_with_grocy/coordinator.py#L58-L69) by that:
```
            data = await self.api.retrieve_data(force)
            if data is not None:
                self.last_successful_fetch = self.hass.loop.time()
                self.data = data  # Ensure data is always updated
                self._parsed_data = (
                    data["homeassistant_products"]
                    if "homeassistant_products" in data
                    else []
                )
            else:
                LOGGER.warning("Received empty or invalid data from API.")
```
and do the same thing for /custom_components/shopping_list_with_grocy/apis/shopping_list_with_grocy.py, replace [this](https://github.com/Anrolosia/Shopping-List-with-Grocy/blob/main/custom_components/shopping_list_with_grocy/apis/shopping_list_with_grocy.py#L552-L569) by that:
```
                titles = [
                    "products",
                    "shopping_lists",
                    "shopping_list",
                    "locations",
                    "stock",
                    "product_groups",
                    "quantity_units",
                ]
                results = await asyncio.gather(
                    *(self.fetch_list(path) for path in titles)
                )

                self.final_data = dict(zip(titles, results))

                parsed_products = await self.parse_products(self.final_data)
                self.final_data["homeassistant_products"] = parsed_products
```

**Comment by schumi2309** [comment]
I testing tomorrow because work !
Thanks.

**Comment by schumi2309** [comment]
ok,
I have 2 shopping lists in grocy, and it created 2 SLWG files for me. with the items in them. That's already a good thing.
But, the items are already checked as if I had already bought, while they are in my list in grocy (to buy)

![Image](https://github.com/user-attachments/assets/d2e2f3eb-5f59-4f50-93ca-8fc8322f11ad)

But we are moving forward, it's great, thank you

**Comment by Anrolosia** [comment]
Perfect, and do you still have errors in the logs? Display raw logs and filter on "shopping"

**Comment by schumi2309** [comment]
No. Nothing error for "shopping"

**Comment by Anrolosia** [comment]
Humm, that's so weird... The status is managed here: https://github.com/Anrolosia/Shopping-List-with-Grocy/blob/main/custom_components/shopping_list_with_grocy/apis/shopping_list_with_grocy.py#L113 and if your grocy shopping list is the same as it was in your previous message (https://github.com/Anrolosia/Shopping-List-with-Grocy/issues/48#issuecomment-2698944965), that's strange because they are not marked as done.
Did you tried to uncheck them? Force a product refresh (/developer-tools/action => Refresh products from Grocy.)?

**Comment by schumi2309** [comment]
I just tested it.
It remains checked.
If I add an item to the shopping list, it is automatically checked. I also tried to add a new shopping list and add an item, same thing, in the second list, the item is checked directly.
If I uncheck, here is the message at the bottom of the screen:

![Image](https://github.com/user-attachments/assets/a90ae9da-e537-41c0-866d-d7b8c02e577f)

**Comment by schumi2309** [comment]
in todo, shopping list, above right, the two little dots: "more information", here is the result:

![Image](https://github.com/user-attachments/assets/fad3573c-98d7-45f8-86a2-4be6c55d178c)

the SLWG shopping list file remains at "0"
I think that there is already a problem there.

**Comment by schumi2309** [comment]
in mqtt, it's an old list, which I have already deleted from Grocy.

in the grocy shopping list integration, all the products are there but I have this on each product:

![Image](https://github.com/user-attachments/assets/630bbbaf-ccf4-424a-bb63-e8f6d83102c8)

**Comment by schumi2309** [comment]
there wouldn't be a problem with mqtt and the grocy api?
that it would take a bad list, following an old code of the api ?

**Comment by schumi2309** [comment]
However, on your card, the shopping list is correct:

![Image](https://github.com/user-attachments/assets/b0d23e2d-1114-4162-968b-8284126180f6)

**Comment by Anrolosia** [comment]
> in mqtt, it's an old list, which I have already deleted from Grocy.
> 
> in the grocy shopping list integration, all the products are there but I have this on each product:
> 
> ![Image](https://github.com/user-attachments/assets/630bbbaf-ccf4-424a-bb63-e8f6d83102c8)

Could you please expand the attributes section? Also, yeah, the MQTT things you have might interfere. You can either download MQTT explorer on Windows and manually delete the old products or you can try to delete the integration, restart home assistant and configure it again. The setup of the integration should take care of the deletion, and since you had an issue with the timeout, it might have been an issue...

**Comment by Anrolosia** [comment]
Only the shopping list with grocy integration. Then restart home assistant and add the integration again.
And no, you will not loose anything, the data is on your grocy instance

**Comment by schumi2309** [comment]
Ok. I test this.

**Comment by schumi2309** [comment]
i don't found my password of MQTT
how to do it ?

**Comment by Anrolosia** [comment]
It's either your HomeAssistant credentials, or the easiest way is to configure your own credential here /hassio/addon/core_mosquitto/config

![Image](https://github.com/user-attachments/assets/dd0065d4-631a-425b-bfd7-f411a3282e9e)

**Comment by schumi2309** [comment]
I created a new person. I think it's good.
I recovered my integration shopping list with grocy with 150 entities. All the articles are at 0.
I'm going to restart HA to be sure, but for now, in mqtt, still the old list, nothing more.

**Comment by schumi2309** [comment]
after restarting HA, everything is in error.

![Image](https://github.com/user-attachments/assets/60c8e005-459b-436b-9481-daf326ad42c5)

**Comment by Anrolosia** [comment]
Ok, so now at least you have more products, that's good.
The update of products happens AFTER home assistant reboot, wait few minutes
Do you still have the info logs enabled for that integration?
You should see something like that:
```
2025-03-04 15:47:29.524 INFO (MainThread) [custom_components.shopping_list_with_grocy] Migration to version 7 successful
2025-03-04 15:47:29.525 INFO (MainThread) [custom_components.shopping_list_with_grocy] 🔄 Initializing Shopping List with Grocy
2025-03-04 15:47:29.525 INFO (MainThread) [custom_components.shopping_list_with_grocy] Migration to version 7 successful
2025-03-04 15:47:29.525 INFO (MainThread) [custom_components.shopping_list_with_grocy] ⏳ Waiting for Home Assistant to fully start...
2025-03-04 15:47:35.553 INFO (MainThread) [custom_components.shopping_list_with_grocy] 🚀 Home Assistant started!
2025-03-04 15:48:02.189 INFO (MainThread) [custom_components.shopping_list_with_grocy.sensor] Setting up sensors for Shopping List with Grocy
2025-03-04 15:48:02.253 INFO (MainThread) [custom_components.shopping_list_with_grocy.todo] Setting up todo for Shopping List with Grocy
```

**Comment by Anrolosia** [comment]
![Image](https://github.com/user-attachments/assets/38b21258-1fd3-4d22-b7b7-23810e3817db)

**Comment by schumi2309** [comment]
I did recover the 150 articles, but here is the message on each article:

![Image](https://github.com/user-attachments/assets/dde77f80-6f16-4e6c-9dd7-98fff6ed78d6)

**Comment by Anrolosia** [comment]
Also, the issue is maybe due to your mayonnaise aux oeufs, it seems there is weird characters in there (according to your log)

**Comment by Anrolosia** [comment]
yeah, that's ok, I do have the same thing, but trust me, it's still there

**Comment by Anrolosia** [comment]
> ![Image](https://github.com/user-attachments/assets/6fc8647e-bdb9-4ff1-8993-201cc3d30376)

That's not possible, you had logs just before. But displaying them in a raw format, you should at least have the logs your showed previously man :)
Remove the filter to see if your logs are working fine.

**Comment by Anrolosia** [comment]
Neither do I.
Like I said, try to remove the filter (shopping) and browse the logs by yourself.

**Comment by schumi2309** [comment]
I just went with mqtt explorer to delete the old list and also the egg mayonnaise. so the old list is no longer in my mqtt
always the same thing in SLWG:

![Image](https://github.com/user-attachments/assets/4f0164f0-b230-41ba-9aa8-dc11a9ab7b16)

![Image](https://github.com/user-attachments/assets/76d3c41b-d3d5-476e-ae58-c84716e54316)

log:

![Image](https://github.com/user-attachments/assets/1f941513-09cd-49e1-841a-72cb62f1be3c)

![Image](https://github.com/user-attachments/assets/01bd6251-d616-42b6-bbfe-34c38a00c09c)

![Image](https://github.com/user-attachments/assets/a0bad8f7-4a14-45a5-b2d9-cec38169d29a)

![Image](https://github.com/user-attachments/assets/d5b66429-b5bc-4ba9-8d22-f87359a43c9d)

**Comment by schumi2309** [comment]
![Image](https://github.com/user-attachments/assets/da5b5098-f215-4bc3-8204-ccc53edf0e4c)

![Image](https://github.com/user-attachments/assets/3f8f71d1-db3b-4452-92d5-21f59ea600d6)

**Comment by Anrolosia** [comment]
I will try to do something for you tomorrow, maybe it will help

**Comment by Anrolosia** [comment]
Ok, that's a bit better!
Would you mind testing the following for me:
- restart home assistant and wait for the entities to be synced
- find your product "canette Coca Lidl", click on it and click on "Attributs" at the bottom 
- take a screenshot and send it it please

**Comment by schumi2309** [comment]
after 10 minutes, the entities are still not synchronized. I had to do a refresh on the integration.

![Image](https://github.com/user-attachments/assets/b6a5ad11-ab16-4100-a0bb-5dd67ae2a9b7)

once this is done, all my articles are in sync.

but I don't have "attribute".

![Image](https://github.com/user-attachments/assets/b5ee435c-6ab4-42a9-a388-68629a9686a5)

**Comment by Anrolosia** [comment]
Should be at the bottom

![Image](https://github.com/user-attachments/assets/feb0cf8d-03b7-4d82-9522-e4ac8a728777)

Also, you don't have to to reload the integration to have your entity, you can use the service "Shopping List with Grocy - Refresh products" instead

**Comment by Anrolosia** [comment]
You could also add with your file editor a log here: /homeassistant/custom_components/shopping_list_with_grocy/todo.py and go line 169. Replace
```
    shopping_lists = api.build_item_list(coordinator.data)
```
with
```
    shopping_lists = api.build_item_list(coordinator.data)
    LOGGER.info(shopping_lists)
```
save, and restart. Check your **raw** logs

**Comment by schumi2309** [comment]
but I don't have "attribute". at the bottom of the page

![Image](https://github.com/user-attachments/assets/b76e8efb-46f5-4cb4-810c-3a18fdd6ecdf)

**Comment by schumi2309** [comment]
![Image](https://github.com/user-attachments/assets/0d9c4c0a-b580-475f-b210-77c0761eb959)

**Comment by schumi2309** [comment]
if I do a product refresh, they are "unavailable"
so every time I start, I have to refresh the integration, otherwise, it doesn't work

**Comment by Anrolosia** [comment]
As I'm not able to reproduce your issue, and it seems you're the only one with that, you will have to dig a bit.
This is what you can do:
- Open /homeassistant/custom_components/shopping_list_with_grocy/apis/shopping_list_with_grocy.py and add a log before line 375:
```
        LOGGER.debug("Parsed products: %s", parsed_products)
```
- Open /homeassistant/custom_components/shopping_list_with_grocy/sensor.py and modify log line 144:
```
        LOGGER.debug("Adding/updating entity: %s with attributes: %s", entity_id, product["attributes"])
```
- Open /homeassistant/custom_components/shopping_list_with_grocy/sensor.py and add a log before line 375:
```
        LOGGER.debug("Creating sensor for product: %s with attributes: %s", product.get("name"), product.get("attributes"))
```
- Open /homeassistant/custom_components/shopping_list_with_grocy/coordinator.py and add a log before line 74:
```
                LOGGER.debug("Parsed data in coordinator: %s", self._parsed_data)
```
Restart homeassistant and send me the log. Please use a copy paste un a texte file or something instead of a picture

Be careful, it will be a massive log! But sadly this is the only way I can try to help you

**Comment by schumi2309** [comment]
is it normal that sensor.py only has 329 lines because you tell me to add a line before 375??

**Comment by schumi2309** [comment]
Should I do an integration refresh before looking at the log or not?

**Comment by Anrolosia** [comment]
Do not please. I want to see the real logs. Doing an integration refresh without a reboot after is never a good idea

**Comment by schumi2309** [comment]
[home-assistant_2025-03-07T16-24-49.413Z.log](https://github.com/user-attachments/files/19129966/home-assistant_2025-03-07T16-24-49.413Z.log)

this is my log comply

**Comment by Anrolosia** [comment]
Could you please check the indentation of ```LOGGER.debug("Adding/updating entity: %s with attributes: %s", entity_id, product["attributes"])```
I see that in your logs:
```
 File "/config/custom_components/shopping_list_with_grocy/sensor.py", line 144
    LOGGER.debug("Adding/updating entity: %s with attributes: %s", entity_id, product["attributes"])
IndentationError: unexpected indent[0m
```
So the rest will be pointless because nothing is loaded. Thanks

**Comment by schumi2309** [comment]
[home-assistant_2025-03-07T16-40-43.571Z.log](https://github.com/user-attachments/files/19130184/home-assistant_2025-03-07T16-40-43.571Z.log)

if still problem, show me where to put it exactly.
Thanks

**Comment by Anrolosia** [comment]
Still not good. I will do the modification and send you the files, but later today, right now I have to take care of my family

**Comment by schumi2309** [comment]
yes, of course, no worries. there's no hurry.
thanks again.

**Comment by schumi2309** [comment]
this:

[home-assistant_shopping_list_with_grocy_2025-03-07T19-10-11.938Z.log](https://github.com/user-attachments/files/19132221/home-assistant_shopping_list_with_grocy_2025-03-07T19-10-11.938Z.log)

**Comment by Anrolosia** [comment]
I'm checking your logs right now! There is something that pops: You have some kind of icons/emojis in location names? Maybe this is because of that. I will check and get back to you

**Comment by schumi2309** [comment]
ok, thanks.

**Comment by Anrolosia** [comment]
Please take this file here, and replace it, then restart:
https://github.com/Anrolosia/Shopping-List-with-Grocy/commit/4e22654ed0eb4009a9475dff3a6a623ca3a2e33e

**Comment by schumi2309** [comment]
[home-assistant_shopping_list_with_grocy_2025-03-07T19-41-13.774Z.log](https://github.com/user-attachments/files/19132581/home-assistant_shopping_list_with_grocy_2025-03-07T19-41-13.774Z.log)

**Comment by schumi2309** [comment]
Every time I restart, this is what I get:

![Image](https://github.com/user-attachments/assets/acd6d3a5-95fe-494b-8412-be778a0355af)

**Comment by Anrolosia** [comment]
I might have understood your issue, give me few minutes and I will send you a new file to test.
Also, you definitely have to use the logs from what I sent here : https://github.com/Anrolosia/Shopping-List-with-Grocy/issues/48#issuecomment-2707188842, doing so I shouldn't have logs from your other integrations

**Comment by schumi2309** [comment]
is this the way I just sent you the last two logs?
save, stop, then save the log.
is this what I posted?

**Comment by schumi2309** [comment]
I think I understood the mistake, is it better like this?

logger:
  default: info
  logs:
    #custom_components.teamtracker: debug
    #custom_components.hacs: debug
    #aiogithubapi: debug
    #pyaarlo: debug
    custom_components.shopping_list_with_grocy: info

**Comment by schumi2309** [comment]
don't hesitate to tell me what to do or send me a file. But there, unfortunately I have to leave you tonight, I'm going to work. I'll look at your answer tomorrow morning, and give you a follow-up...
once again, thank you for everything.

**Comment by Anrolosia** [comment]
Sorry, it was a bit longer to go over modifications and logs
Here is what you can try: https://github.com/Anrolosia/Shopping-List-with-Grocy/commit/8c529ec629daa77c5cf48b10d7b37a7a63ec6865
Good luck with work!

**Comment by schumi2309** [comment]
[home-assistant_shopping_list_with_grocy_2025-03-08T09-39-53.137Z.log](https://github.com/user-attachments/files/19142820/home-assistant_shopping_list_with_grocy_2025-03-08T09-39-53.137Z.log)

**Comment by schumi2309** [comment]
This is the phenomenon I have when I update my card:
everything updates, with my different product images, then, like a rollback, it erases all of them one after the other and returns as before the update.
I made a video, but he doesn't want to take it here.

Before:

![Image](https://github.com/user-attachments/assets/7f7bde32-c863-4d4d-9917-c2fc875fd2fb)

during:

![Image](https://github.com/user-attachments/assets/720e7ff6-b65a-4ab5-bb68-78e5285fcb31)

after:

![Image](https://github.com/user-attachments/assets/8c94d32f-f214-4f3f-923b-612f59561e95)

**Comment by schumi2309** [comment]
and always the same, all checked.

![Image](https://github.com/user-attachments/assets/da242fcb-8658-4d1a-a2fd-60503c48b1b6)

**Comment by Anrolosia** [comment]
I pushed a new version, would my mind testing those modifications please?
https://github.com/Anrolosia/Shopping-List-with-Grocy/commit/afce58aa2aa5e568a0f636af3788e5c21af48fb9

**Comment by schumi2309** [comment]
[home-assistant_shopping_list_with_grocy_2025-03-09T08-32-18.099Z.log](https://github.com/user-attachments/files/19148350/home-assistant_shopping_list_with_grocy_2025-03-09T08-32-18.099Z.log)

**Comment by schumi2309** [comment]
I still don't understand why I still don't have anything that goes into MQTT, wouldn't there be a problem on this side with the shopping list and MQTT connection? Connection and password problem or something else?

**Comment by schumi2309** [comment]
if it helps, i saw this in the grocy add-on:

![Image](https://github.com/user-attachments/assets/67571167-a4c8-4f84-a58d-44dab9fc7c78)

**Comment by Anrolosia** [comment]
First of all, you sent the log, but you're not mentioning anything about the behavior, is it working now? Because according to your logs, it should now.
Second, as mentioned in the release notes since v0.19.0 (https://github.com/Anrolosia/Shopping-List-with-Grocy/releases/tag/v0.19.0), MQTT is not used anymore for the creation of sensors, so I don't know what did you tried to accomplish here.
Back in the days I asked you if you were running grocy via the addon in HomeAssistant, you never answered, but now I see you do.
Is your homeassistant installed on a Raspberry pi? And if so, which generation? Because it could be a performance issue... Maybe you can check the processor and memory usage when you are refreshing the products?

**Comment by schumi2309** [comment]
Sorry if I was not complete in my explanations:
Shopping list runs on HA with the add-on, all on a Home Assistant Blue 

![Image](https://github.com/user-attachments/assets/82341fcb-bc18-4dd9-9f4d-bfc4c03eeda2) 
with HA OS supervisor.

Here are the memories used:

![Image](https://github.com/user-attachments/assets/1bb49851-1388-4805-918c-0ec7a6f0be77)

![Image](https://github.com/user-attachments/assets/cdf48085-3053-4253-8c56-5d1235ab1a5a)

My 2 remaining concerns are that my card updates with all my items, then everything returns to "undefined" as shown above.
and the second is that my shopping list in TODO is always crossed out, noted as already purchased.


![Image](https://github.com/user-attachments/assets/ad179a0d-ad4d-4337-9210-ef7b804c5eb0)

If you have any further questions please don't hesitate and sorry for forgetting some things.

**Comment by Anrolosia** [comment]
New test for you: https://github.com/Anrolosia/Shopping-List-with-Grocy/commit/4cbaad3825bfd6a31ad1bce7c1c9440b906144ba

I changed a lot of things, so please be careful, you have to take all the files I modified.

Also, no need for the logs this time, I want to check the behavior you will have now.

Finaly, an other thing I'll need if for you to go to your grocy instance, and navigate to the REST API browser, then test that one

![Image](https://github.com/user-attachments/assets/f8d00886-765c-4c48-9416-d3cbdbd3c135)

and send me the result json please

Thanks

**Comment by schumi2309** [comment]
![Image](https://github.com/user-attachments/assets/2c9feeb6-6604-4f76-8b76-951332734f59)

![Image](https://github.com/user-attachments/assets/7b367ed6-a1c2-4003-be80-1d32a6767da4)

Here is the text that is in the value schema example box:

[
  {
    "id": "1",
    "name": "Cookies",
    "description": null,
    "location_id": "4",
    "qu_id_purchase": "3",
    "qu_id_stock": "3",
    "min_stock_amount": "8",
    "default_best_before_days": "0",
    "row_created_timestamp": "2019-05-02 20:12:26",
    "product_group_id": "1",
    "picture_file_name": "cookies.jpg",
    "default_best_before_days_after_open": "0",
    "enable_tare_weight_handling": "0",
    "tare_weight": "0.0",
    "not_check_stock_fulfillment_for_recipes": "0",
    "shopping_location_id": null,
    "userfields": null,
    "should_not_be_frozen": "1",
    "default_consume_location_id": "5",
    "move_on_open": "1"
  },
  {
    "id": 0,
    "name": "string",
    "description": "string",
    "period_type": "manually",
    "period_config": "string",
    "period_days": 0,
    "track_date_only": true,
    "rollover": true,
    "assignment_type": "no-assignment",
    "assignment_config": "string",
    "next_execution_assigned_to_user_id": 0,
    "start_date": "2025-03-10T09:35:31.863Z",
    "rescheduled_date": "2025-03-10T09:35:31.863Z",
    "rescheduled_next_execution_assigned_to_user_id": 0,
    "row_created_timestamp": "2025-03-10T09:35:31.863Z",
    "userfields": {}
  },
  {
    "id": 0,
    "name": "string",
    "description": "string",
    "used_in": "string",
    "charge_interval_days": 0,
    "row_created_timestamp": "2025-03-10T09:35:31.864Z",
    "userfields": {}
  },
  {
    "id": "2",
    "name": "0",
    "description": null,
    "row_created_timestamp": "2019-05-02 20:12:25",
    "userfields": null
  },
  {
    "id": "2",
    "name": "Piece",
    "description": null,
    "row_created_timestamp": "2019-05-02 20:12:25",
    "name_plural": "Pieces",
    "plural_forms": null,
    "userfields": null
  },
  {
    "id": 0,
    "shopping_list_id": 0,
    "product_id": 0,
    "note": "string",
    "amount": 0,
    "row_created_timestamp": "2025-03-10T09:35:31.864Z",
    "userfields": {}
  },
  {
    "id": "77",
    "product_id": "1",
    "amount": "2",
    "best_before_date": "2019-07-07",
    "purchased_date": "2019-05-03",
    "stock_id": "5ccc6b2421979",
    "price": null,
    "open": "0",
    "opened_date": null,
    "row_created_timestamp": "2019-05-03 18:24:04",
    "location_id": "4",
    "shopping_location_id": null
  },
  {
    "product_id": 0,
    "barcode": "string",
    "qu_id": 0,
    "shopping_location_id": 0,
    "amount": 0,
    "last_price": 0,
    "note": "string"
  }
]

regarding the result of the update:

My shopping list in TODO is still checked, on the other hand in my card shopping list, it is well refreshed and remains. that is impeccable, it is back to normal.

![Image](https://github.com/user-attachments/assets/0d72a7e1-0c6d-443b-8bc0-1b21134f753e)

**Comment by Anrolosia** [comment]
You have to click on "Try it out" and select "shopping_list" as in my example, and then click on Execute, and send me what you have in server response please

Great for your products, we're moving in the right direction!

**Comment by schumi2309** [comment]
on the other hand not all are updated, even after a refresh:

![Image](https://github.com/user-attachments/assets/6f781378-8b57-4564-9778-da2850aeaad3)

![Image](https://github.com/user-attachments/assets/c9b09891-2438-4dfd-aea5-bc54a4fcba9a)

![Image](https://github.com/user-attachments/assets/f2092ff8-7cfe-448e-a8f6-e95d6d58eb7f)

![Image](https://github.com/user-attachments/assets/f7c9531b-56a1-4bbc-85d5-c28045a67fe5)

but I recovered the attributes

**Comment by schumi2309** [comment]
here when I click on execute:

![Image](https://github.com/user-attachments/assets/6be2b968-bce2-462b-8b8d-c089fd108c80)

**Comment by schumi2309** [comment]
This ?

[
  {
    "id": "1",
    "name": "Cookies",
    "description": null,
    "location_id": "4",
    "qu_id_purchase": "3",
    "qu_id_stock": "3",
    "min_stock_amount": "8",
    "default_best_before_days": "0",
    "row_created_timestamp": "2019-05-02 20:12:26",
    "product_group_id": "1",
    "picture_file_name": "cookies.jpg",
    "default_best_before_days_after_open": "0",
    "enable_tare_weight_handling": "0",
    "tare_weight": "0.0",
    "not_check_stock_fulfillment_for_recipes": "0",
    "shopping_location_id": null,
    "userfields": null,
    "should_not_be_frozen": "1",
    "default_consume_location_id": "5",
    "move_on_open": "1"
  },
  {
    "id": 0,
    "name": "string",
    "description": "string",
    "period_type": "manually",
    "period_config": "string",
    "period_days": 0,
    "track_date_only": true,
    "rollover": true,
    "assignment_type": "no-assignment",
    "assignment_config": "string",
    "next_execution_assigned_to_user_id": 0,
    "start_date": "2025-03-10T10:09:30.052Z",
    "rescheduled_date": "2025-03-10T10:09:30.052Z",
    "rescheduled_next_execution_assigned_to_user_id": 0,
    "row_created_timestamp": "2025-03-10T10:09:30.052Z",
    "userfields": {}
  },
  {
    "id": 0,
    "name": "string",
    "description": "string",
    "used_in": "string",
    "charge_interval_days": 0,
    "row_created_timestamp": "2025-03-10T10:09:30.052Z",
    "userfields": {}
  },
  {
    "id": "2",
    "name": "0",
    "description": null,
    "row_created_timestamp": "2019-05-02 20:12:25",
    "userfields": null
  },
  {
    "id": "2",
    "name": "Piece",
    "description": null,
    "row_created_timestamp": "2019-05-02 20:12:25",
    "name_plural": "Pieces",
    "plural_forms": null,
    "userfields": null
  },
  {
    "id": 0,
    "shopping_list_id": 0,
    "product_id": 0,
    "note": "string",
    "amount": 0,
    "row_created_timestamp": "2025-03-10T10:09:30.052Z",
    "userfields": {}
  },
  {
    "id": "77",
    "product_id": "1",
    "amount": "2",
    "best_before_date": "2019-07-07",
    "purchased_date": "2019-05-03",
    "stock_id": "5ccc6b2421979",
    "price": null,
    "open": "0",
    "opened_date": null,
    "row_created_timestamp": "2019-05-03 18:24:04",
    "location_id": "4",
    "shopping_location_id": null
  },
  {
    "product_id": 0,
    "barcode": "string",
    "qu_id": 0,
    "shopping_location_id": 0,
    "amount": 0,
    "last_price": 0,
    "note": "string"
  }
]

**Comment by schumi2309** [comment]
Response headers:

<div style="box-sizing: border-box; color: rgb(59, 65, 81); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgba(97, 175, 254, 0.1); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
access-control-allow-headers: *  access-control-allow-methods: GET,POST,PUT,DELETE,OPTIONS  access-control-allow-origin: *  connection: keep-alive  content-type: application/json  date: Mon,10 Mar 2025 10:09:30 GMT  server: nginx  transfer-encoding: chunked  x-content-type-options: nosniff  x-powered-by: PHP/8.2.26  x-robots-tag: none  x-xss-protection: 1; mode=block
--


</div><br class="Apple-interchange-newline">

**Comment by Anrolosia** [comment]
No. Should be something like that:
```
[
  {
    "id": "6530",
    "product_id": "16",
    "note": "out_of_stock",
    "amount": "1",
    "row_created_timestamp": "2025-03-03 15:39:05",
    "shopping_list_id": "1",
    "done": "0",
    "qu_id": "3"
  },
  {
    "id": "6534",
    "product_id": "222",
    "note": "out_of_stock",
    "amount": "1",
    "row_created_timestamp": "2025-03-03 15:39:58",
    "shopping_list_id": "1",
    "done": "0",
    "qu_id": "3"
  },
  {
    "id": "6549",
    "product_id": "12",
    "note": "out_of_stock",
    "amount": "1",
    "row_created_timestamp": "2025-03-04 11:47:29",
    "shopping_list_id": "1",
    "done": "0",
    "qu_id": "3"
  },
  {
    "id": "6582",
    "product_id": "61",
    "note": null,
    "amount": "1",
    "row_created_timestamp": "2025-03-06 22:35:40",
    "shopping_list_id": "1",
    "done": "0",
    "qu_id": "3"
  },
  {
    "id": "6583",
    "product_id": "200",
    "note": null,
    "amount": "1",
    "row_created_timestamp": "2025-03-06 22:35:40",
    "shopping_list_id": "1",
    "done": "0",
    "qu_id": "3"
  }
]
```

**Comment by schumi2309** [comment]
[
  {
    "id": "1",
    "name": "Cookies",
    "description": null,
    "location_id": "4",
    "qu_id_purchase": "3",
    "qu_id_stock": "3",
    "min_stock_amount": "8",
    "default_best_before_days": "0",
    "row_created_timestamp": "2019-05-02 20:12:26",
    "product_group_id": "1",
    "picture_file_name": "cookies.jpg",
    "default_best_before_days_after_open": "0",
    "enable_tare_weight_handling": "0",
    "tare_weight": "0.0",
    "not_check_stock_fulfillment_for_recipes": "0",
    "shopping_location_id": null,
    "userfields": null,
    "should_not_be_frozen": "1",
    "default_consume_location_id": "5",
    "move_on_open": "1"
  },
  {
    "id": 0,
    "name": "string",
    "description": "string",
    "period_type": "manually",
    "period_config": "string",
    "period_days": 0,
    "track_date_only": true,
    "rollover": true,
    "assignment_type": "no-assignment",
    "assignment_config": "string",
    "next_execution_assigned_to_user_id": 0,
    "start_date": "2025-03-10T10:09:30.052Z",
    "rescheduled_date": "2025-03-10T10:09:30.052Z",
    "rescheduled_next_execution_assigned_to_user_id": 0,
    "row_created_timestamp": "2025-03-10T10:09:30.052Z",
    "userfields": {}
  },
  {
    "id": 0,
    "name": "string",
    "description": "string",
    "used_in": "string",
    "charge_interval_days": 0,
    "row_created_timestamp": "2025-03-10T10:09:30.052Z",
    "userfields": {}
  },
  {
    "id": "2",
    "name": "0",
    "description": null,
    "row_created_timestamp": "2019-05-02 20:12:25",
    "userfields": null
  },
  {
    "id": "2",
    "name": "Piece",
    "description": null,
    "row_created_timestamp": "2019-05-02 20:12:25",
    "name_plural": "Pieces",
    "plural_forms": null,
    "userfields": null
  },
  {
    "id": 0,
    "shopping_list_id": 0,
    "product_id": 0,
    "note": "string",
    "amount": 0,
    "row_created_timestamp": "2025-03-10T10:09:30.052Z",
    "userfields": {}
  },
  {
    "id": "77",
    "product_id": "1",
    "amount": "2",
    "best_before_date": "2019-07-07",
    "purchased_date": "2019-05-03",
    "stock_id": "5ccc6b2421979",
    "price": null,
    "open": "0",
    "opened_date": null,
    "row_created_timestamp": "2019-05-03 18:24:04",
    "location_id": "4",
    "shopping_location_id": null
  },
  {
    "product_id": 0,
    "barcode": "string",
    "qu_id": 0,
    "shopping_location_id": 0,
    "amount": 0,
    "last_price": 0,
    "note": "string"
  }
]

**Comment by Anrolosia** [comment]
Ok, great, I know why it's checked for you by default now.
I will work on something for you to test, and we'll see :)
Thank you

**Comment by schumi2309** [comment]
thank you especially...

**Comment by schumi2309** [comment]
looking at the weird things, I also see that for example:
strawberry drink, in stock, it gives me 1000 but my stock is at zero!

![Image](https://github.com/user-attachments/assets/cd0ee5a4-fe97-48bc-8d74-a80ed2b33f9a)

![Image](https://github.com/user-attachments/assets/6c8490b7-8b6b-4712-851e-5fec1ae79caa)

if this can help you...

**Comment by Anrolosia** [comment]
Could you test that commit please? https://github.com/Anrolosia/Shopping-List-with-Grocy/commit/d9aace39b5c90363b107fd984127bf9c5d43e9f3
Hopefuly it will fix both your shopping list and weird data

**Comment by schumi2309** [comment]
hip hip hip hooray...
it works. I'll test it a bit more but it looks good, very good even. My card is correct, and my shopping list is just without anything checked.
Now, simple question, if I check an article in TODO, it doesn't affect anything in Grocy?
In any case, I thank you for all this time that you have devoted to me, you are great.
it's super awesome!

![Image](https://github.com/user-attachments/assets/1c1f1f6e-2418-4d56-a56d-9a1abf8013f8)

![Image](https://github.com/user-attachments/assets/eaa72e53-73a2-4ee4-9f5f-88d278f03b64)

![Image](https://github.com/user-attachments/assets/5122bbb0-ff9d-488c-8758-98f9c8fe6444)

**Comment by schumi2309** [comment]
I will not fail to test any new version for you, it will be with great pleasure.

not to ask too much, but is there a way to export the SLWG shopping list file to Notes in ios for example?
or make a shortcut in HA to open the shopping list without having to open HA?

this may not be your particular field, and if so, I understand very well.
otherwise, just to know if it is possible.

**Comment by Anrolosia** [comment]
I pushed the new version, update the integration in HACS and let me know if everything is good now, thanks

**Comment by schumi2309** [comment]
everything seems correct to me I would even say impeccable. super nice work you deserve it, after having bored you for days! but now it's perfect.

**Comment by Anrolosia** [comment]
Awesome! I will close that issue now, and if you have any other issue, don't hesitate to open a new issue.
In the meantime, if you want, don't hesitate to buy me a coffee :)
<a href="https://www.buymeacoffee.com/anrolosia">
    <img src="https://img.shields.io/badge/buy%20me%20a%20coffee-donate-yellow?style=for-the-badge" alt="Donate Coffee" />
  </a>
