### ISSUE TITLE
`todo` integration does not show lists

### ISSUE THREAD

**Issue by jeroenterheerdt** [Anrolosia/Shopping-List-with-Grocy#51]
As previously discussed in #46 ...
I still don't see anything in my todo and the states say:

![Image](https://github.com/user-attachments/assets/0be9124b-85c1-4839-84ac-c5f4a190017c)

This is what the log says:
```
Logger: homeassistant.config_entries
Source: config_entries.py:753
First occurred: 8:36:12 AM (1 occurrences)
Last logged: 8:36:12 AM

Error setting up entry ShoppingListWithGrocy for shopping_list_with_grocy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 753, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/shopping_list_with_grocy/__init__.py", line 65, in async_setup_entry
    migration_success = await async_migrate_entry(hass, entry)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/shopping_list_with_grocy/__init__.py", line 334, in async_migrate_entry
    await hass.async_block_till_done()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1015, in async_block_till_done
    await self._await_and_log_pending(tasks)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1038, in _await_and_log_pending
    _, pending = await asyncio.wait(pending, timeout=BLOCK_LOG_TIMEOUT)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 451, in wait
    return await _wait(fs, timeout, return_when, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 537, in _wait
    await waiter
asyncio.exceptions.CancelledError: Global task timeout
```

**Comment by Anrolosia** [comment]
Is it with the version v0.19.3?

Thanks

**Comment by jeroenterheerdt** [comment]
Yes

**Comment by Anrolosia** [comment]
I just pushed v0.19.4, would you mind testing it? Thanks

**Comment by jeroenterheerdt** [comment]
it seems to work now. the only issue I still see is that it takes a while to have items show up after they are added on the shopping list in Grocy. I believe it happens every 30 seconds but I think it should be configurable. For me, I'd want to have the list sync at least every 10 seconds.

**Comment by Anrolosia** [comment]
Great.
It's not really recommended to go under 30 sec for a refresh on Home Assistant, especially for some under performing configurations (like Rpi 4)
But you can trigger a product refresh / update using the service dedicated for that (go to /developer-tools/action and search for Shopping List With Grocy). You can even add an automation for that service to be triggered every 10 seconds.
I will close that ticket now since it's working as intended, thanks
